

variables:
  RestoreBuildProjects: '**/*.csproj'


stages:
  - stage: Build
    displayName: Deploy to App Service
    jobs:
    - job: Build
      pool:
        vmImage: ubuntu-20.04
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '$(Parameters.RestoreBuildProjects)'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '$(Parameters.RestoreBuildProjects)'

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--output $(build.artifactstagingdirectory)'
          zipAfterPublish: True

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()
        
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'website'
          publishLocation: 'pipeline'
  
  - stage: Deploy
    displayName: Deploy to Azure App Service
    jobs:
      - job: Deploy
        pool:
          vmImage: windows-latest
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Visual Studio Ultimate with MSDN(d2d9ddb9-e1e6-468e-8f8e-7789613307a2)'
            appType: 'webApp'
            WebAppName: 'fithnesswebapp32'
            packageForLinux: '$(Pipeline.Workspace)/**/website.zip'
            AppSettings: '-Message "Deployed with YAML"'

